sudo: required
services:
  - docker

before_install:
  - docker build -t kiwueke/react-test -f./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kiwueke/react-test npm test

after_success:
  - docker build -t kiwueke/multi-client ./client
  - docker build -t kiwueke/multi-nginx ./nginx
  - docker build -t kiwueke/multi-server ./server
  - docker build -t kiwueke/multi-worker ./worker
  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push kiwueke/multi-client
  - docker push kiwueke/multi-nginx
  - docker push kiwueke/multi-server
  - docker push kiwueke/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-832718289545
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
